baseURL = "/"
title = "Radio League of America"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Radio League of America" # title for frontpage, may include image
copyright = ""
description = 'A future vision for supporting <br />a more modern and diverse amateur radio<br />'
#startbuttonText = "Activate"
#startbuttonLink = "#"
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[params.one]
enable = true
title = 'Amateur Radio Representation & Services<br />for the Rest of Us'
body = '''
The amateur radio community is too large, and too diverse to be represented by a single
national entity. The ARRL does a significant amount of very important advocacy and lobbying work for
amateur radio at a national level, but it's membership consists of only 20% of licensed amateurs.
An unknown portion of the other 80%, and some of the 20%, are dissatisfied because the ARRL can not, 
or does not provide the services or representation that reflect their diverse backgrounds, needs, or desires. The 
Radio League of America is currently just an idea being discussed in many circles, under many different
names, to provide services in our amateur radio community to those who's voices are not represented at 
a national level.
'''

[[params.one.icon]]
icon = "fa-circle-user"
style = "1"
label = "People"

[[params.one.icon]]
icon = "fa-heart"
style = "2"
label = "Love"

[[params.one.icon]]
icon = "solid fa-landmark"
style = "3"
label = "Representation"

[params.two]
enable = true

[[params.two.section]]
img = "img/pic01.jpg"
title = 'History of the <br />Radio League of America'
body = '''
There was a time when more than one national ham radio organization existed. The Radio League of America was one
of several in the early days of amateur radio, and were actually the [first to successfully complete a transcontinental relay.](https://earlyradiohistory.us/sec012.htm#part070)
'''

[[params.two.section]]
img = "img/pic02.jpg"
title = 'Reviving the Radio League of America'
body = '''
While the final name of a new organization may be something different, with it's history of being another option, at the forefront of amateur radio technology and service, the RLA
makes an excellent umbrella to start consolidating and gathering the ideas that have been expressed around the need for another
option in our modern and diverse world.
'''

[[params.two.section]]
img = "img/pic03.jpg"
title = 'Would you like to contribute?'
body = '''
  Now is an excellent time to have your voice heard. We are currently just a collection of hams, who have started to attempt
to gather our thoughts collectively in one space. Our current mission is to see if building something like this, for us, is
possible.  
  
  [Join us on Discord](https://discord.gg/MY8xqYEMq) and tell us your thoughts, or to ask for access to contribute to our Notion documentation where we have begun
to gather our thoughts.  
  
  If you are not a user of Discord, more options will be coming soon, but in the meantime you can 
  send an email to admin@radioleagueofamerica.org and we can get you set up to help out.
'''

[params.three]
enable = false
title = 'Accumsan mus tortor nunc aliquet'
body = '''
Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend  
fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.
'''

[[params.three.feature]]
icon = "fa-paper-plane"
title = "Arcu accumsan"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-laptop"
title = "Ac Augue Eget"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-code"
title = "Foo bar"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "solid fa-headphones-alt"
title = "Baz kram"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-heart"
title = "Some latin text"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-flag"
title = "Nothing important"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = false
title = "Arcue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false

[params.contact]
enable = false
title = "Contact"
body = "Leave us a message."
phone = "+49 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "nospam@example.com"
subject = "New Submission!"
formspree_form_id = "example_invalid"

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = ""
youtube = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"

[languages.es]
weight = 10
languageName = "Español"

